<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>🏛️ Museum - make main structure you web app</title>
    <link rel="stylesheet" href="source/css/pages/index/index.css">
</head>

<body>
    <header></header>

    <main>
        <div class="welcome">
            <span>🏛️</span>
            <h1>Welcome to Museum</h1>
        </div>

        <div class="info">
            <p>This is a stub. If you see this page, it means that it is under development. This page was automatically
                generated by museum. This is an open-source project that allows you to quickly create a basic website
                architecture. With a few commands, museum allows you to create a basic page (which you are currently
                seeing), registration and login pages, as well as a dashboard.
            </p>
        </div>

        <div class="media">
            <button onclick="window.location.href='login/'">Login page</button>
            <button onclick="window.location.href='registration/'">Registration page</button>
            <button onclick="window.location.href='dashboard/'">Dashboard page</button>
            <button onclick="window.location.href='logout/'">Logout</button>
        </div>

        <div class="media">
            <a href="https://github.com/bulatik205/museum">
                <img src="source/imges/GitHub_Invertocat_Black_Clearspace.png" alt="">
            </a>
        </div>
    </main>

    <footer class="footer">
        <div class="footer__logo">
            🏛️
        </div>

        <div class="footer__desc">
            <p>Museum — open source project.
                You can freely use, study, and modify the code.
                If you distribute a modified version publicly, you must do so under the GNU GPL v2 (or later)
                license and open the source code.</p>
        </div>

        <div class="footer__founder">
            Developer: <a href="https://github.com/bulatik205">bulatik205</a>
        </div>
    </footer>
</body>

</html>